/****************************************************************************
	This file was generated by Golific.

	Do not edit this file. If you do, your changes will be overwritten the next
	time 'generate' is invoked.
******************************************************************************/

package main

import (
	"encoding/json"
	"log"
	"strconv"
	"strings"
)

/******************************************************************************
	ENUM SUMMARY

Oof (type OofEnum, uint8)
	Bar 1 "bar" "bar"
	Baz 123 "Baz" "Baz"
	Buz 3 "Buz" "Some description"

Animal (type AnimalEnum, uint8)
	Dog 1 "doggy" "Your best friend, and you know it."
	Cat 0 "kitty" "Your best friend, but doesn't always show it."
	Horse 3 "horsie" "Everyone loves horses."
******************************************************************************/

/*****************************

Tester struct

******************************/
func NewTester() *Tester {
	return &Tester{
		private: private_zettozge441d{
			Test2: "foo",
		},
		AnimalEnum: &Animal.Dog,
		Test4:      "bar",
	}
}

// A struct to test the @struct descriptor
//
// And another line or two for good measure
type Tester struct {
	private private_zettozge441d
	*AnimalEnum
	// The fourth item
	Test4    string
	Test5    string
	*FooEnum `whatever`
}

type private_zettozge441d struct {
	// The first item
	Test1 string `json:"test1"`
	Test2 string
	Test3 string
}

type json_zettozge441d struct {
	*private_zettozge441d
	*AnimalEnum
	Test4    string
	Test5    string
	*FooEnum `whatever`
}

func (self *Tester) Test2() string {
	return self.private.Test2
}

func (self *Tester) SetTest3(v string) {
	self.private.Test3 = v
}

func (self *Tester) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_zettozge441d{
		&self.private,
		self.AnimalEnum,
		self.Test4,
		self.Test5,
		self.FooEnum,
	})
}

func (self *Tester) UnmarshalJSON(j []byte) error {
	var temp json_zettozge441d
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_zettozge441d
	self.AnimalEnum = temp.AnimalEnum
	self.Test4 = temp.Test4
	self.Test5 = temp.Test5
	self.FooEnum = temp.FooEnum
	return nil
}

/*****************************

FooEnum - bit flags

******************************/

type FooEnum struct{ value_1rh035n7ga0oi uint8 }

var Foo = struct {
	Bar FooEnum
	Baz FooEnum
	Buz FooEnum

	// foobar is an array of all variants. Useful in range loops.
	foobar [3]FooEnum
}{
	Bar: FooEnum{value_1rh035n7ga0oi: 1},
	Baz: FooEnum{value_1rh035n7ga0oi: 2},
	Buz: FooEnum{value_1rh035n7ga0oi: 4},
}

func init() {
	Foo.foobar = [3]FooEnum{
		Foo.Bar, Foo.Baz, Foo.Buz,
	}
}

// Value returns the numeric value of the variant as a uint8.
func (self FooEnum) Value() uint8 {
	return self.value_1rh035n7ga0oi
}

// IntValue is the same as 'Value()', except that the value is cast to an 'int'.
func (self FooEnum) IntValue() int {
	return int(self.value_1rh035n7ga0oi)
}

// Name returns the name of the variant as a string.
func (self FooEnum) Name() string {
	switch self.value_1rh035n7ga0oi {
	case 1:
		return "Bar"
	case 2:
		return "Baz"
	case 4:
		return "Buz"
	}

	return ""
}

// Type returns the variant's type name as a string.
func (self FooEnum) Type() string {
	return "FooEnum"
}

// Namespace returns the variant's namespace name as a string.
func (self FooEnum) Namespace() string {
	return "Foo"
}

// IsDefault returns true if the variant was designated as the default value.
func (self FooEnum) IsDefault() bool {
	return false && self.value_1rh035n7ga0oi == 0
}

// String returns the given string value of the variant. If none has been set,
// its return value is as though 'Name()' had been called.
// If multiple bit values are assigned, the string values will be joined into a
// single string using "," as a separator.
func (self FooEnum) String() string {
	switch self.value_1rh035n7ga0oi {
	case 1:
		return "bar"
	case 2:
		return "baz"
	case 4:
		return "Buz"
	}

	if self.value_1rh035n7ga0oi == 0 {
		return ""
	}

	var vals = make([]string, 0, 3/2)

	for _, item := range Foo.foobar {
		if self.value_1rh035n7ga0oi&item.value_1rh035n7ga0oi == item.value_1rh035n7ga0oi {
			vals = append(vals, item.String())
		}
	}
	return strings.Join(vals, ",")
}

// Description returns the description of the variant. If none has been set, its
// return value is as though 'String()' had been called.
func (self FooEnum) Description() string {
	switch self.value_1rh035n7ga0oi {
	case 1:
		return "bar"
	case 2:
		return "This is the description"
	case 4:
		return "Buz"
	}
	return ""
}

// JSON marshaling methods
func (self FooEnum) MarshalJSON() ([]byte, error) {
	return []byte(strconv.Quote(self.String())), nil
}

func (self *FooEnum) UnmarshalJSON(b []byte) error {
	var s, err = strconv.Unquote(string(b))
	if err != nil {
		return err
	}

	if len(s) == 0 {
		return nil
	}

	switch s {
	case "bar":
		self.value_1rh035n7ga0oi = 1
		return nil
	case "baz":
		self.value_1rh035n7ga0oi = 2
		return nil
	case "Buz":
		self.value_1rh035n7ga0oi = 4
		return nil
	}

	var val = 0

	for _, part := range strings.Split(string(b), ",") {
		switch part {
		case "bar":
			val |= 1
		case "baz":
			val |= 2
		case "Buz":
			val |= 4
		default:
			log.Printf("Unexpected value: %q while unmarshaling FooEnum\n", part)
		}
	}

	self.value_1rh035n7ga0oi = uint8(val)
	return nil
}

// Bitflag enum methods

// Add returns a copy of the variant with the value of 'v' added to it.
func (self FooEnum) Add(v FooEnum) FooEnum {
	self.value_1rh035n7ga0oi |= v.value_1rh035n7ga0oi
	return self
}

// AddAll returns a copy of the variant with all the values of 'v' added to it.
func (self FooEnum) AddAll(v ...FooEnum) FooEnum {
	for _, item := range v {
		self.value_1rh035n7ga0oi |= item.value_1rh035n7ga0oi
	}
	return self
}

// Remove returns a copy of the variant with the value of 'v' removed from it.
func (self FooEnum) Remove(v FooEnum) FooEnum {
	self.value_1rh035n7ga0oi &^= v.value_1rh035n7ga0oi
	return self
}

// RemoveAll returns a copy of the variant with all the values of 'v' removed
// from it.
func (self FooEnum) RemoveAll(v ...FooEnum) FooEnum {
	for _, item := range v {
		self.value_1rh035n7ga0oi &^= item.value_1rh035n7ga0oi
	}
	return self
}

// Has returns 'true' if the receiver contains the value of 'v', otherwise
// 'false'.
func (self FooEnum) Has(v FooEnum) bool {
	return self.value_1rh035n7ga0oi&v.value_1rh035n7ga0oi == v.value_1rh035n7ga0oi
}

// HasAny returns 'true' if the receiver contains any of the values of 'v',
// otherwise 'false'.
func (self FooEnum) HasAny(v ...FooEnum) bool {
	for _, item := range v {
		if self.value_1rh035n7ga0oi&item.value_1rh035n7ga0oi == item.value_1rh035n7ga0oi {
			return true
		}
	}
	return false
}

// HasAll returns 'true' if the receiver contains all the values of 'v',
// otherwise 'false'.
func (self FooEnum) HasAll(v ...FooEnum) bool {
	for _, item := range v {
		if self.value_1rh035n7ga0oi&item.value_1rh035n7ga0oi != item.value_1rh035n7ga0oi {
			return false
		}
	}
	return true
}

/*****************************

OofEnum

******************************/

type OofEnum struct{ value_sy778bh8jlsz uint8 }

var Oof = struct {
	Bar OofEnum
	Baz OofEnum
	Buz OofEnum

	// Values is an array of all variants. Useful in range loops.
	Values [3]OofEnum
}{
	Bar: OofEnum{value_sy778bh8jlsz: 1},
	Baz: OofEnum{value_sy778bh8jlsz: 123},
	Buz: OofEnum{value_sy778bh8jlsz: 3},
}

func init() {
	Oof.Values = [3]OofEnum{
		Oof.Bar, Oof.Baz, Oof.Buz,
	}
}

// Value returns the numeric value of the variant as a uint8.
func (self OofEnum) Value() uint8 {
	return self.value_sy778bh8jlsz
}

// IntValue is the same as 'Value()', except that the value is cast to an 'int'.
func (self OofEnum) IntValue() int {
	return int(self.value_sy778bh8jlsz)
}

// Name returns the name of the variant as a string.
func (self OofEnum) Name() string {
	switch self.value_sy778bh8jlsz {
	case 1:
		return "Bar"
	case 123:
		return "Baz"
	case 3:
		return "Buz"
	}

	return ""
}

// Type returns the variant's type name as a string.
func (self OofEnum) Type() string {
	return "OofEnum"
}

// Namespace returns the variant's namespace name as a string.
func (self OofEnum) Namespace() string {
	return "Oof"
}

// IsDefault returns true if the variant was designated as the default value.
func (self OofEnum) IsDefault() bool {
	return false && self.value_sy778bh8jlsz == 0
}

// String returns the given string value of the variant. If none has been set,
// its return value is as though 'Name()' had been called.

func (self OofEnum) String() string {
	switch self.value_sy778bh8jlsz {
	case 1:
		return "bar"
	case 123:
		return "Baz"
	case 3:
		return "Buz"
	}

	return ""
}

// Description returns the description of the variant. If none has been set, its
// return value is as though 'String()' had been called.
func (self OofEnum) Description() string {
	switch self.value_sy778bh8jlsz {
	case 1:
		return "bar"
	case 123:
		return "Baz"
	case 3:
		return "Some description"
	}
	return ""
}

// JSON marshaling methods
func (self OofEnum) MarshalJSON() ([]byte, error) {
	return []byte(strconv.Itoa(int(self.value_sy778bh8jlsz))), nil
}

func (self *OofEnum) UnmarshalJSON(b []byte) error {
	var n, err = strconv.ParseUint(string(b), 10, 64)
	if err != nil {
		return err
	}
	self.value_sy778bh8jlsz = uint8(n)
	return nil
}

/*****************************

AnimalEnum

******************************/

// An enum to test the @enum descriptor
type AnimalEnum struct{ value_8fuv4t2cay0v uint8 }

var Animal = struct {
	// Dog is a dog
	Dog AnimalEnum
	// Cat is a cat
	Cat AnimalEnum
	// Horse is a horse (of course)
	Horse AnimalEnum

	// Values is an array of all variants. Useful in range loops.
	Values [3]AnimalEnum
}{
	Dog:   AnimalEnum{value_8fuv4t2cay0v: 1},
	Cat:   AnimalEnum{value_8fuv4t2cay0v: 0},
	Horse: AnimalEnum{value_8fuv4t2cay0v: 3},
}

func init() {
	Animal.Values = [3]AnimalEnum{
		Animal.Dog, Animal.Cat, Animal.Horse,
	}
}

// Value returns the numeric value of the variant as a uint8.
func (self AnimalEnum) Value() uint8 {
	return self.value_8fuv4t2cay0v
}

// IntValue is the same as 'Value()', except that the value is cast to an 'int'.
func (self AnimalEnum) IntValue() int {
	return int(self.value_8fuv4t2cay0v)
}

// Name returns the name of the variant as a string.
func (self AnimalEnum) Name() string {
	switch self.value_8fuv4t2cay0v {
	case 1:
		return "Dog"
	case 0:
		return "Cat"
	case 3:
		return "Horse"
	}

	return ""
}

// Type returns the variant's type name as a string.
func (self AnimalEnum) Type() string {
	return "AnimalEnum"
}

// Namespace returns the variant's namespace name as a string.
func (self AnimalEnum) Namespace() string {
	return "Animal"
}

// IsDefault returns true if the variant was designated as the default value.
func (self AnimalEnum) IsDefault() bool {
	return true && self.value_8fuv4t2cay0v == 0
}

// String returns the given string value of the variant. If none has been set,
// its return value is as though 'Name()' had been called.

func (self AnimalEnum) String() string {
	switch self.value_8fuv4t2cay0v {
	case 1:
		return "doggy"
	case 0:
		return "kitty"
	case 3:
		return "horsie"
	}

	return ""
}

// Description returns the description of the variant. If none has been set, its
// return value is as though 'String()' had been called.
func (self AnimalEnum) Description() string {
	switch self.value_8fuv4t2cay0v {
	case 1:
		return "Your best friend, and you know it."
	case 0:
		return "Your best friend, but doesn't always show it."
	case 3:
		return "Everyone loves horses."
	}
	return ""
}

// JSON marshaling methods
func (self AnimalEnum) MarshalJSON() ([]byte, error) {
	return []byte(strconv.Quote(self.String())), nil
}

func (self *AnimalEnum) UnmarshalJSON(b []byte) error {
	var s, err = strconv.Unquote(string(b))
	if err != nil {
		return err
	}

	if len(s) == 0 {
		return nil
	}

	switch s {
	case "doggy":
		self.value_8fuv4t2cay0v = 1
		return nil
	case "kitty":
		self.value_8fuv4t2cay0v = 0
		return nil
	case "horsie":
		self.value_8fuv4t2cay0v = 3
		return nil
	default:
		log.Printf("Unexpected value: %q while unmarshaling AnimalEnum\n", s)
	}

	return nil
}
